{
  "hash": "04ef03d24a7c3495480fc8e5eb57a135",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Modeling: Adjusted Effect Estimates\"\npackages: [dplyr, broom]\n---\n\n\n\n::: {.callout-note appearance=\"minimal\"}\n**Packages covered in this part:** [dplyr](https://dplyr.tidyverse.org/), [broom](https://cran.r-project.org/package=broom)\n:::\n\n\n\nThe [previous chapter](describing-and-testing.qmd) left you with a cliffhanger.\nYour cross-tabs showed two clear things: case fatality climbs steeply with age,\nand — separately — hospitalized cases die far more often than non-hospitalized\nones. Both are real signals. But they're tangled together. Older people are\n*also* the ones most likely to be hospitalized, so when you look at\nhospitalization and death in a cross-tab, some of what you're seeing is really\njust age wearing a different hat.\n\nA two-way table can't pull those apart. It only ever looks at one relationship\nat a time. What you need is a way to ask: *what is the effect of age on death,\nholding hospitalization and sex constant?* And at the same time, *what is the\neffect of hospitalization, holding age and sex constant?* That \"holding the\nothers constant\" is exactly what a **regression** does, and it's exactly what a\nstakeholder means when they ask for **adjusted effect estimates**.\n\nThis chapter fits a **logistic regression** — the workhorse model for a\nyes/no outcome like *died* — and reads the results as **odds ratios** with\nconfidence intervals. If this is your first model in R, don't worry: we'll take\nit a piece at a time and translate every number into a plain sentence.\n\n::: {.callout-warning}\n## This models fake data\n\nEverything here runs on the **synthetic** line-list from the\n[Building a Dataset](../building-a-dataset/index.qmd) chapter. The town names\nand case counts are real, but every age, sex, hospitalization, and death was\nrandomly generated. The patterns are real-*shaped* — deaths really do skew old\n— but **no row is a real person.** Never report one of these odds ratios as a\nreal finding. They exist only so you can practice the mechanics on data that\nbehaves like the real thing.\n:::\n\n## From cross-tab to model\n\nThe previous chapter's tools — chi-square, Fisher's, the trend test — each\nanswer a question about *one* pair of variables. Regression answers a different\nkind of question: given *several* predictors at once, what does each one\ncontribute on its own? The model estimates every effect **net of the others**,\nwhich is the whole point. When it tells you the odds ratio for age, that number\nalready has hospitalization and sex accounted for.\n\n::: {.callout-note}\n## This chapter uses broom\n\nWe'll use **broom** to turn the model's output into a tidy data frame. It may\nnot be installed yet. In your own `covid-briefing/` project, install it once\nwith:\n\n```r\ninstall.packages(\"broom\")\n```\n\nIf you're building this book from its repository (which uses `renv`), install\nit into the project library instead and record it in the lockfile:\n\n```r\nrenv::install(\"broom\")\nrenv::snapshot()\n```\n\n`broom` takes the somewhat awkward object that `glm()` hands back and turns it\ninto a clean, rectangular data frame you can read, filter, and drop into a\nreport — the same shape as everything else you've worked with.\n:::\n\n## Fit a logistic regression\n\nA little prep first. Two small but important setup moves before we fit\nanything.\n\n**First, an ordered age variable with a deliberate reference level.** A\nregression with a categorical predictor doesn't estimate an effect for *every*\nlevel — it picks one level as the baseline (the \"reference\") and reports every\nother level *relative to it*. We make `age_group` a `factor` and put `\"18-49\"`\nfirst, which makes it the reference. That's a choice with meaning: healthy\nworking-age adults are the natural comparison group, so every age odds ratio\nwill read as \"compared to a 18–49-year-old.\" Reference-first is a habit worth\nbuilding.\n\n**Second, a numeric 0/1 outcome.** Logistic regression models the probability\nof an *event* happening, so it needs the outcome coded as `1` for the event\n(died) and `0` for not. Our `died` column is `\"Yes\"`/`\"No\"` text;\n`as.integer(died == \"Yes\")` turns it into exactly the `1`/`0` the model wants.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(broom)\n\nmodel_data <-\n  linelist |>\n  mutate(\n    age_group = factor(\n      case_when(\n        age < 18 ~ \"0-17\",\n        age < 50 ~ \"18-49\",\n        age < 65 ~ \"50-64\",\n        age < 80 ~ \"65-79\",\n        TRUE     ~ \"80+\"\n      ),\n      levels = c(\"18-49\", \"0-17\", \"50-64\", \"65-79\", \"80+\")\n    ),\n    died_flag = as.integer(died == \"Yes\")\n  )\n```\n:::\n\n\nNow the model itself. `glm()` — **g**eneralized **l**inear **m**odel — is the\nfunction, and the two arguments that make it a *logistic* regression are the\nformula and the `family`.\n\nThe formula `died_flag ~ age_group + sex + hospitalized` reads left to right as\n\"**died explained by** age group, plus sex, plus hospitalization.\" The `~` is\n\"is modeled by\"; the `+` signs add predictors. `family = binomial` is the piece\nthat makes this logistic: it tells `glm()` the outcome is a yes/no event and to\nwork on the **log-odds** scale rather than fitting a straight line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- glm(\n  died_flag ~ age_group + sex + hospitalized,\n  data = model_data,\n  family = binomial\n)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = died_flag ~ age_group + sex + hospitalized, family = binomial, \n    data = model_data)\n\nCoefficients:\n                Estimate Std. Error z value Pr(>|z|)    \n(Intercept)     -5.40346    0.11523 -46.894  < 2e-16 ***\nage_group0-17   -1.68075    0.51183  -3.284  0.00102 ** \nage_group50-64   0.78213    0.15321   5.105 3.31e-07 ***\nage_group65-79   2.49119    0.12776  19.499  < 2e-16 ***\nage_group80+     4.00982    0.12665  31.660  < 2e-16 ***\nsexMale          0.02561    0.07499   0.341  0.73275    \nhospitalizedYes  1.41159    0.08274  17.060  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 8421.1  on 35221  degrees of freedom\nResidual deviance: 5696.3  on 35215  degrees of freedom\nAIC: 5710.3\n\nNumber of Fisher Scoring iterations: 9\n```\n\n\n:::\n:::\n\n\n`summary()` prints the full model report — the same one SAS's `PROC LOGISTIC`\nwould give you, if you're coming from that world. There's a lot there, but the\nkey thing to know right now is that the numbers in the `Estimate` column are on\nthe **log-odds** scale. A log-odds coefficient is nearly impossible to read\ndirectly — nobody thinks in log-odds. That's why we almost never stop here.\nThe next step converts these into **odds ratios**, which you *can* read.\n\n## Odds ratios with broom\n\nHere's where `broom` earns its keep. `tidy()` takes the model and returns a\ntidy data frame, one row per term. Two arguments do the heavy lifting:\n`exponentiate = TRUE` converts those log-odds coefficients into **odds ratios**,\nand `conf.int = TRUE` adds a **95% confidence interval** for each one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(model, exponentiate = TRUE, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 7\n  term            estimate std.error statistic   p.value conf.low conf.high\n  <chr>              <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n1 (Intercept)      0.00450    0.115    -46.9   0          0.00357   0.00560\n2 age_group0-17    0.186      0.512     -3.28  1.02e-  3  0.0569    0.447  \n3 age_group50-64   2.19       0.153      5.10  3.31e-  7  1.62      2.95   \n4 age_group65-79  12.1        0.128     19.5   1.13e- 84  9.44     15.6    \n5 age_group80+    55.1        0.127     31.7   5.50e-220 43.2      71.1    \n6 sexMale          1.03       0.0750     0.341 7.33e-  1  0.886     1.19   \n7 hospitalizedYes  4.10       0.0827    17.1   2.93e- 65  3.49      4.82   \n```\n\n\n:::\n:::\n\n\nNow every number is legible. The `estimate` column is the odds ratio, and\n`conf.low`/`conf.high` bracket the 95% CI. Here's how to read an odds ratio:\n\n- **Greater than 1** means *higher* odds of the outcome than the reference.\n- **Less than 1** means *lower* odds.\n- **Exactly 1** means no difference at all.\n\nAnd crucially — every one of these is **adjusted** for the other predictors in\nthe model. Walk the age gradient, each compared to the 18–49 reference group:\n\n- **`age_group0-17`: 0.19** (95% CI 0.06–0.45). Children have about a fifth the\n  odds of death of a working-age adult — far *lower*, which is why the OR sits\n  well below 1.\n- **`age_group50-64`: 2.19** (1.62–2.95). Roughly double the odds.\n- **`age_group65-79`: 12.1** (9.44–15.6). Twelve times the odds.\n- **`age_group80+`: 55.1** (43.2–71.1). Fifty-five times the odds of death of a\n  working-age adult — a dramatic age gradient, and all of it *after* adjusting\n  for whether the person was hospitalized.\n\nThen the other two predictors:\n\n- **`hospitalizedYes`: 4.10** (3.49–4.82). Hospitalized cases have about four\n  times the odds of death — and, importantly, this is the hospitalization\n  effect *with age already accounted for*. It's not just older people showing\n  up again in disguise.\n- **`sexMale`: 1.03** (0.89–1.19). This one is the teaching moment. The odds\n  ratio is a hair above 1, but look at the confidence interval: it runs from\n  0.89 to **1.19** — it *crosses 1*.\n\nThat last point deserves its own paragraph. When a confidence interval crosses\n1, the data can't distinguish the effect from \"no effect at all.\" The interval\nincludes odds ratios below 1 (protective) *and* above 1 (harmful), so you\ngenuinely cannot say which direction, if any, sex pushes the outcome. This is a\n**null adjusted estimate**, and it's a clean, concrete example of one. Contrast\nit with the previous chapter's habit of eyeballing a cross-tab and declaring a\npattern: here the model gives you a principled way to say \"no, there's nothing\nto see in this variable\" — the interval says so.\n\nA nice sanity check falls out of all this. Remember *how* the synthetic data\nwas built: with a strong age effect baked in, no sex effect, and a\nhospitalization bump. The model **recovered exactly that structure** — a steep\nage gradient, a null result for sex, a moderate hospitalization effect. When a\nmodel reproduces the signal you know is in the data, that's reassurance about\nboth the model *and* the data build.\n\n::: {.callout-warning}\n## An odds ratio is not a risk ratio\n\nPeople often read an odds ratio as if it were a *risk* ratio (\"55× the risk\"),\nbut the two only agree when the outcome is **rare**. For a common outcome the\nodds ratio exaggerates the risk ratio, sometimes badly. Death is uncommon\nenough here that the gap is modest, but keep the distinction in mind — say\n\"odds,\" not \"risk,\" when you report an OR.\n:::\n\n## The tidymodels way\n\nThe `glm()` you just ran is the right tool for this job. When your goal is an\n**explanatory** model — you want an interpretable effect estimate, an adjusted\nodds ratio to hand a stakeholder — plain `glm()` plus `broom` is lean, clear,\nand hard to beat.\n\nThere's another whole ecosystem in the tidyverse for modeling, called\n**tidymodels**, and it's worth knowing where it fits. Its real strength is\n**prediction**: when the goal isn't \"explain\" but \"forecast,\" tidymodels gives\nyou train/test splits, resampling, hyperparameter tuning, and standardized\nperformance metrics, all with a consistent interface. That's a different job\nfrom what we did above.\n\nBut two of tidymodels' habits are worth borrowing even for an explanatory\nmodel: **recipes** for declaring your preprocessing once, and **parsnip** for a\nmodel spec you can re-point at a different engine without rewriting. Here's the\nsame logistic regression, expressed the tidymodels way. We're showing it as a\nreference — it does **not** run when the book builds — so you can read the shape\nof it without needing tidymodels installed:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(recipes)\nlibrary(parsnip)\nlibrary(workflows)\n\n# died as a factor outcome for classification; first level is the reference\nmodel_data <- model_data |>\n  mutate(died = factor(died, levels = c(\"No\", \"Yes\")))\n\n# 1. recipe: declare outcome + predictors and preprocessing (dummy-code factors)\ndeath_recipe <-\n  recipe(died ~ age_group + sex + hospitalized, data = model_data) |>\n  step_dummy(all_nominal_predictors())\n\n# 2. parsnip spec: logistic regression via the glm engine\ndeath_spec <-\n  logistic_reg() |>\n  set_engine(\"glm\")\n\n# 3. workflow bundles preprocessing + model and fits in one place\ndeath_fit <-\n  workflow() |>\n  add_recipe(death_recipe) |>\n  add_model(death_spec) |>\n  fit(data = model_data)\n\n# same tidy odds-ratio table, now from the workflow\ntidy(death_fit, exponentiate = TRUE, conf.int = TRUE)\n```\n:::\n\n\nWhat each piece buys you:\n\n- **recipes** — reproducible preprocessing, declared once and reused. Here it's\n  just dummy-coding the factors, but the same idea scales: `step_other()` to\n  collapse rare categories into an \"other\" bucket, `step_normalize()` to center\n  and scale continuous predictors, and dozens more. You write the recipe once\n  and every fit and prediction uses the identical steps.\n- **parsnip** — one model spec, swappable engines. `logistic_reg()` is the\n  *kind* of model; `set_engine(\"glm\")` picks the implementation. Want a\n  penalized version instead? Swap in `set_engine(\"glmnet\")` and you don't\n  rewrite the fit.\n- **workflows** — bundle the recipe and the model together so they can't drift\n  apart. The preprocessing and the model travel as one object, which is a\n  genuine reproducibility win on a bigger project.\n\n**When should you actually reach for full tidymodels?** When the goal is\nprediction. That's when you'll add `rsample` for train/test splits and\ncross-validation, and `yardstick` for metrics like ROC-AUC and accuracy. For an\nadjusted odds ratio, though — a single explanatory model you want to interpret —\n`glm()` and `broom` are lighter and clearer, and there's no prize for\nover-tooling. The full prediction track lives at\n<https://www.tidymodels.org/>.\n\nOne gotcha to file away: `logistic_reg()` needs a **factor** outcome (not the\n0/1 integer `glm()` wanted), and tidymodels treats the **first** factor level as\nthe reference — the *non*-event. That's why the code above sets the levels as\n`c(\"No\", \"Yes\")` deliberately, so that `\"Yes\"` (death) is the event being\nmodeled. Set your factor levels on purpose; don't let the default alphabetical\norder decide which outcome you're predicting.\n\n## Wrap-up\n\nYou fit a real adjusted model. You took a tangle that a cross-tab couldn't\nresolve — is it age, or is it hospitalization? — and got a clean answer for\neach: an odds ratio, adjusted for the others, with a confidence interval that\ntells you how much to trust it. You saw a strong effect (age), a moderate one\n(hospitalization), and a genuinely null one (sex, its CI straddling 1), and you\nlearned to read all three off a single tidy table. And you saw where the\ntidyverse's bigger modeling toolkit fits, and where it's more machine than the\njob needs.\n\nOne honest gap remains. Everything here is about **odds** — the odds that a\n*known case* died. It says nothing about **rates** in a *population*:\nage-adjusted death rates, incidence-rate ratios, the per-100,000 measures that\nmuch of surveillance runs on. Those need a **population denominator** — how many\npeople live in each town and age band — which this book doesn't have in its data\nyet. When a denominator dataset lands, a future chapter can take up rate-based\nmeasures. Until then, you've got the case-level model that answers the\nstakeholder's actual question: the adjusted effect estimates.\n\n::: {.callout-note}\nWant this chapter as a runnable script? See\n[`project-snapshots/line-list-practice`](https://github.com/CT-DPH-Data-Management-and-Governance/modern-r-for-public-health-practitioners/tree/main/project-snapshots/line-list-practice)\non GitHub. `03_model_deaths.R` is the script version of the logistic regression\nand odds-ratio table you just built, ready to drop into your `scripts/` folder.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}