project:
  type: book
  output-dir: docs

book:
  title: "Modern R for Public Health Practitioners"
  subtitle: "CT DPH DMAG Training"
  author: "Alexander Senetcky, MPH"
  date: "06/22/2026"
  description: >
    A project-based course for public health practitioners who
    want to become confident R users by buidling a report
    that grows with every chapter.

  search: true
  repo-url: https://github.com/CT-DPH-Data-Management-and-Governance/modern-r-for-public-health-practitioners
  repo-actions: [edit]

  sidebar:
    style: floating

  page-footer:
    left: |
      This is a proof of concept.
    right: |
      This is a proof of concept.


  chapters:
    - index.qmd
    - preface.qmd
    - part: "Introduction and Process"
      chapters:
        - chapters/orientation/index.qmd
        - chapters/orientation/introduction.qmd
    - part: "Working with real data"
      chapters:
        - chapters/working-with-real-data/index.qmd
        - chapters/working-with-real-data/reading-comma-delimited-files.qmd
        - chapters/apis-functions/index.qmd
        - chapters/apis-functions/project.qmd
    - part: "Security Basics"
      chapters:
        - chapters/secrets/index.qmd
    - part: "Further Reading"
      chapters:
        - chapters/further-reading/index.qmd
  page-navigation: true


format:
  html:
    theme:
      light: [cosmo, theme-ctdph.scss]
    code-copy: true
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto
  echo: true
  warning: false
  message: false



