{
  "hash": "4459686b578fdd8ef3f0073a083d4db2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Describing and Testing\"\npackages: [dplyr, janitor]\n---\n\n\n\n::: {.callout-note appearance=\"minimal\"}\n**Packages covered in this part:** [dplyr](https://dplyr.tidyverse.org/), [janitor](https://sfirke.github.io/janitor/)\n:::\n\n\n\nYou built a line-list in the last chapter — one row per case, with an age, a\nset of dates, and outcome flags. Now we get to *ask questions of it*. This\nchapter is the everyday inferential toolkit: describe what's in the data,\ncross-tabulate one variable against another, and run the handful of statistical\ntests that answer \"is this pattern real, or could it be chance?\"\n\nIf you're coming from SAS, this is `PROC FREQ` and `PROC MEANS` territory —\njust tidier, and with the whole thing scriptable end to end.\n\n::: {.callout-warning}\n## This analysis runs on fake data\n\nEverything below runs on the **synthetic** line-list from the\n[previous chapter](../building-a-dataset/index.qmd). The town names and case\ncounts are real, but every age, sex, date, and outcome was randomly generated.\nThe *shape* of the patterns is realistic — deaths really do skew older — but\n**no row is a real person.** Never report these numbers as real, and never let\none of these tables walk out the door as if it described actual patients.\n:::\n\n## Getting set up\n\nWe'll lean on two packages: `dplyr` for the summarising and `janitor` for the\nepi-friendly tables. In your own `covid-briefing/` project you'd start by\nreading the file you built:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinelist <- read_csv(here(\"data\", \"synthetic-covid-linelist.csv\"))\n```\n:::\n\n\nThen we recreate the `age_group` column from the previous chapter — most of the\nquestions in this chapter are about how outcomes vary *across ages*, and a\nhandful of ordered bands is far easier to tabulate than raw years:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(janitor)\n\nlinelist <- linelist |>\n  mutate(\n    age_group = case_when(\n      age < 18 ~ \"0-17\",\n      age < 50 ~ \"18-49\",\n      age < 65 ~ \"50-64\",\n      age < 80 ~ \"65-79\",\n      TRUE     ~ \"80+\"\n    )\n  )\n```\n:::\n\n\n## Section 1 — Describing what you have\n\nBefore any test, look at the data. The first question about almost any outcome\nis simply *how often did it happen?* — counts and percents.\n\n`janitor::tabyl()` is the tool for that. Hand it a column and it returns a tidy\ntable of counts and proportions; `adorn_pct_formatting()` turns the raw\nproportions into readable percentages. If you've reached for `PROC FREQ` in\nSAS, this is the same job.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinelist |>\n  tabyl(died) |>\n  adorn_pct_formatting()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n died     n percent\n   No 34316   97.4%\n  Yes   906    2.6%\n```\n\n\n:::\n:::\n\n\nThat's your case fatality snapshot: about 2.6% of cases in this line-list died.\n`tabyl()` is a data frame like any other, so it drops straight into a report or\na `gt` table later without any wrestling.\n\nCounts answer \"how many.\" For a continuous variable like age you want the\n*shape* — where the middle sits and how far it spreads. `summarise()` gives you\nwhichever statistics you name, and the classic epi move is to compute them\n**split by outcome** so you can compare. Here's \"does age differ between people\nwho died and people who survived?\":\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinelist |>\n  group_by(died) |>\n  summarise(\n    n = n(),\n    mean_age   = round(mean(age), 1),\n    median_age = median(age),\n    min_age    = min(age),\n    max_age    = max(age)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  died      n mean_age median_age min_age max_age\n  <chr> <int>    <dbl>      <dbl>   <dbl>   <dbl>\n1 No    34316     41.4         41       0     100\n2 Yes     906     74.8         79       0     100\n```\n\n\n:::\n:::\n\n\nRead across the two rows and the story jumps out. Among the people who died,\nthe mean age is about 74.8 and the median 79; among survivors the mean is 41.4\nand the median 41. Deaths skew old — decades older, on average. The `mean` and\n`median` sitting close together within each group also tells you neither is\nbeing dragged around by a few extreme outliers.\n\nThis one table is often the whole descriptive section of a briefing. But it\nalso raises the obvious follow-up: we can *see* that deaths are older, but is\nthe association between age and death strong enough to trust? That's what the\nnext section is for.\n\n## Section 2 — Cross-tabulation with a statistical test\n\nThe natural next step is a **two-way table**: age group down the side, outcome\nacross the top. `tabyl()` takes two variables and builds exactly that, and the\n`adorn_*` helpers layer on the pieces you want to see.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinelist |>\n  tabyl(age_group, died) |>\n  adorn_totals(\"row\") |>\n  adorn_percentages(\"row\") |>\n  adorn_pct_formatting() |>\n  adorn_ns()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n age_group             No         Yes\n      0-17 99.9%  (4,598)  0.1%   (4)\n     18-49 99.5% (17,542)  0.5%  (85)\n     50-64 98.8%  (7,491)  1.2%  (88)\n     65-79 92.8%  (3,604)  7.2% (281)\n       80+ 70.7%  (1,081) 29.3% (448)\n     Total 97.4% (34,316)  2.6% (906)\n```\n\n\n:::\n:::\n\n\nThere's a lot packed into that pipe, so here's what each adornment does:\n\n- `adorn_totals(\"row\")` adds a totals row across the bottom.\n- `adorn_percentages(\"row\")` converts each cell to a **row** percentage — so\n  each age group's numbers add to 100% *across* its own row.\n- `adorn_pct_formatting()` formats those as percents.\n- `adorn_ns()` puts the raw counts back in, in parentheses, so you never lose\n  sight of how many people each percentage rests on.\n\nWhy row percents? Because the row is the age group, so the percentage in the\n`Yes` column is the **case fatality rate within that age group** — exactly the\nnumber an epidemiologist wants. Reading down that `Yes` column, the CFR climbs\nsteadily: roughly 0.1% for 0–17, 0.5% for 18–49, 1.2% for 50–64, 7.2% for\n65–79, and 29.3% for the 80+ group. Nearly three in ten of the oldest cases\ndied. That's the association from Section 1, now resolved group by group.\n\nSeeing a trend in a table and *establishing* it statistically are two different\nthings. A **chi-square test** asks whether the association between age group and\noutcome could plausibly have arisen by chance if the two were actually\nunrelated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_died <- table(linelist$age_group, linelist$died)\nchisq.test(age_died)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  age_died\nX-squared = 5176.2, df = 4, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n`table()` builds the plain contingency table (chi-square wants counts, not\npercentages), and `chisq.test()` does the rest. The null hypothesis is that\nthere is **no association** — that outcome doesn't depend on age group. The test\nreturns a huge X-squared statistic (around 5176) on 4 degrees of freedom and a\np-value below 2.2e-16, which is R's way of printing \"smaller than I bother to\nshow.\" In plain terms: if age and death were truly unrelated, a table this\nlopsided would essentially never happen. We reject the null.\n\n::: {.callout-warning}\n## A tiny p-value is not a big effect\n\nWith this many cases, almost *any* association will come back \"significant\" —\nthe p-value is partly a measure of your sample size. A huge `n` makes the test\nexquisitely sensitive, so it will flag even trivial differences. Don't let a\nrow of zeros after the decimal point fool you into thinking you've found\nsomething important. The **effect size** — the actual jump from 0.1% to 29.3%\nCFR you read off the cross-tab — is what makes this finding matter. The\np-value only tells you it's not noise; the percentages tell you it's a big\ndeal.\n:::\n\n### When cells are small: Fisher's exact test\n\nChi-square relies on an *approximation* that gets shaky when the expected count\nin any cell is small — the usual rule of thumb is that no expected cell should\ndrop below 5. That happens all the time when you slice down to a single small\ntown or a rare outcome. **Fisher's exact test** computes the exact probability\ninstead of approximating it, so it stays honest on sparse tables.\n\nLet's force the situation by looking at one small town, Hartland:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhartland <- linelist |> filter(town == \"Hartland\")\n\ntable(hartland$hospitalized, hartland$died)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     \n      No Yes\n  No  56   0\n  Yes  1   2\n```\n\n\n:::\n\n```{.r .cell-code}\nfisher.test(table(hartland$hospitalized, hartland$died))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  table(hartland$hospitalized, hartland$died)\np-value = 0.001753\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n 4.415925      Inf\nsample estimates:\nodds ratio \n       Inf \n```\n\n\n:::\n:::\n\n\nHartland has only 59 cases, and the `table()` shows why chi-square would\nstruggle: the cells are thin and at least one is a flat zero. `fisher.test()`\nhandles that without complaint and returns a p-value of about 0.0018 — strong\nevidence of an association between being hospitalized and dying, even in this\ntiny slice.\n\nThe teaching point: **reach for Fisher when the counts are small.** If you run\n`chisq.test()` on a sparse table it'll warn you that the approximation may be\nunreliable — that warning is your cue to switch. On small or zero-heavy tables,\nFisher is the trustworthy choice.\n\n## Section 3 — Testing a trend in proportions\n\nThe stakeholder didn't just ask \"is there an association\" — they asked about\n**trends in proportions**, like an outcome rising over time or across ordered\ncategories. A plain chi-square treats the age groups as unordered labels; it\nwould give the same answer if you shuffled them. But our age bands have a\nnatural order, and the interesting claim is specifically that CFR *rises\nmonotonically* from young to old.\n\nThe **test for trend in proportions** (a Cochran–Armitage-style test) is built\nfor that. It needs two things in order: the number of deaths in each group, and\nthe number of cases in each group. We build those with a grouped\n`summarise()`, then `arrange()` to lock in the order:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncfr_by_age <-\n  linelist |>\n  group_by(age_group) |>\n  summarise(deaths = sum(died == \"Yes\"), n = n()) |>\n  arrange(age_group)\n\ncfr_by_age\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  age_group deaths     n\n  <chr>      <int> <int>\n1 0-17           4  4602\n2 18-49         85 17627\n3 50-64         88  7579\n4 65-79        281  3885\n5 80+          448  1529\n```\n\n\n:::\n\n```{.r .cell-code}\nprop.trend.test(cfr_by_age$deaths, cfr_by_age$n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared Test for Trend in Proportions\n\ndata:  cfr_by_age$deaths out of cfr_by_age$n ,\n using scores: 1 2 3 4 5\nX-squared = 2918.6, df = 1, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n`sum(died == \"Yes\")` counts the deaths in each group (a `TRUE`/`FALSE` vector\nsums to the number of `TRUE`s), and `n()` counts everyone. `prop.trend.test()`\ntakes the deaths and the group sizes and asks: is there a **directional**\ntrend in the proportion across these ordered groups?\n\nThe result — X-squared around 2919 on 1 degree of freedom, p below 2.2e-16 —\nsays yes, emphatically: CFR increases in a clear linear fashion across the age\nbands. Because this test uses the *ordering* of the groups, it's a sharper\ninstrument than a plain chi-square when the order is meaningful. It's asking a\nmore specific question (\"does it trend?\") and so gives stronger evidence when\nthe answer is yes.\n\nThe same machinery answers the stakeholder's \"outcome by year\" question\ndirectly: group by year instead of age band, feed the yearly death counts and\ncase counts into `prop.trend.test()` **in chronological order**, and you're\ntesting whether the outcome trended up or down over time. Any ordered grouping\n— age bands, years, weeks of a wave — works the same way.\n\n## Wrap-up\n\nYou can now do the three things that make up the bread-and-butter of case-level\nanalysis: **describe** a line-list with counts and summaries, **cross-tabulate**\ntwo variables and test the association with chi-square or Fisher's exact test,\nand **test a trend** across ordered groups. That's the everyday inferential\ntoolkit, and it'll carry you through most routine surveillance questions.\n\nWhat it *won't* do is untangle variables that move together. Older cases might\nalso be more likely to be hospitalized, or to belong to a particular group — and\nthese simple tests look at one relationship at a time. The next chapter,\n**Modeling**, is how you get *adjusted* effect estimates that hold age, sex, and\nthe rest constant all at once.\n\n::: {.callout-note}\nWant this chapter's work as a runnable script? See\n[`project-snapshots/line-list-practice`](https://github.com/CT-DPH-Data-Management-and-Governance/modern-r-for-public-health-practitioners/tree/main/project-snapshots/line-list-practice)\non GitHub. `02_describe_and_test.R` is the script version of everything above —\nthe tabyls, the chi-square, Fisher's, and the trend test — ready to drop into\nyour `scripts/` folder.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}